### ISSUE TITLE
virustotal detected in nppQCP.dll

### ISSUE THREAD

**Issue by zagk** [nulled666/nppqcp#32]
https://www.virustotal.com/en/file/a37b64fc510d0a528eb55715974a46d2aa99a18ace88e881b3906fef542945ac/analysis/1478833454/

Jiangmin 	AdWare.ELEX.iy 

what is that mean?

**Comment by nulled666** [comment]
This means you can trust Jiangmin's false-positive result to remove this plugin.
Or check the source code yourself and compile it yourself.
Or just keep using it.
